export enum ConstraintErrorKeynameEnum {
    // Array
    ArrayContains = "ARRAY_CONTAINS",
    ArrayInvalid = "ARRAY_INVALID",
    ArrayMaxSize = "ARRAY_MAX_SIZE",
    ArrayMinSize = "ARRAY_MIN_SIZE",
    ArrayNotContains = "ARRAY_NOT_CONTAINS",
    ArrayNotEmpty = "ARRAY_NOT_EMPTY",
    ArrayUnique = "ARRAY_UNIQUE",

    // Common
    Allow = "ALLOW",
    Equals = "EQUALS",
    IsDefined = "IS_DEFINED",
    IsEmpty = "IS_EMPTY",
    IsIn = "IS_IN",
    IsLatitude = "IS_LATITUDE",
    IsLatLong = "IS_LAT_LONG",
    IsLongitude = "IS_LONGITUDE",
    IsNotEmpty = "IS_NOT_EMPTY",
    IsNotIn = "IS_NOT_IN",
    IsOptional = "IS_OPTIONAL",
    NotEquals = "NOT_EQUALS",

    // Date
    InvalidDate = "INVALID_DATE",
    MaxDate = "MAX_DATE",
    MinDate = "MIN_DATE",

    // Number
    IsDivisibleBy = "IS_DIVISIBLE_BY",
    IsNegative = "IS_NEGATIVE",
    IsPositive = "IS_POSITIVE",
    Max = "MAX",
    Min = "MIN",

    // Object
    IsInstance = "IS_INSTANCE",
    IsNotEmptyObject = "IS_NOT_EMPTY_OBJECT",

    // String
    Contains = "CONTAINS",
    IsAlpha = "IS_ALPHA",
    IsAlphanumeric = "IS_ALPHANUMERIC",
    IsAscii = "IS_ASCII",
    IsBase32 = "IS_BASE32",
    IsBase64 = "IS_BASE64",
    IsBIC = "IS_BIC",
    IsBooleanString = "IS_BOOLEAN_STRING",
    IsBtcAddress = "IS_BTC_ADDRESS",
    IsByteLength = "IS_BYTE_LENGTH",
    IsCreditCard = "IS_CREDIT_CARD",
    IsCurrency = "IS_CURRENCY",
    IsDataURI = "IS_DATA_URI",
    IsDateString = "IS_DATE_STRING",
    IsDecimal = "IS_DECIMAL",
    IsEAN = "IS_EAN",
    IsEmail = "IS_EMAIL",
    IsEthereumAddress = "IS_ETHEREUM_ADDRESS",
    IsFirebasePushId = "IS_FIREBASE_PUSH_ID",
    IsFQDN = "IS_FQDN",
    IsFullWidth = "IS_FULL_WIDTH",
    IsHalfWidth = "IS_HALF_WIDTH",
    IsHash = "IS_HASH",
    IsHexadecimal = "IS_HEXADECIMAL",
    IsHexColor = "IS_HEXA_COLOR",
    IsHSL = "IS_HSL",
    IsIBAN = "IS_IBAN",
    IsIdentityCard = "IS_IDENTITY_CARD",
    IsIP = "IS_IP",
    IsISBN = "IS_ISBN",
    IsISIN = "IS_ISIN",
    IsISO8601 = "IS_ISO_8601",
    IsISO31661Alpha2 = "IS_ISO_31661_ALPHA_2",
    IsISO31661Alpha3 = "IS_ISO_31661_ALPHA_3",
    IsISRC = "IS_ISRC",
    IsISSN = "IS_ISSN",
    IsJSON = "IS_JSON",
    IsJWT = "IS_JWT",
    IsLocale = "IS_LOCALE",
    IsLowercase = "IS_LOWERCASE",
    IsMacAddress = "IS_MAC_ADDRESS",
    IsMagnetUri = "IS_MAGNET_URI",
    IsMilitaryTime = "IS_MILITARY_TIME",
    IsMobilePhone = "IS_MOBILE_PHONE",
    IsMongoId = "IS_MONGO_ID",
    IsMultiByte = "IS_MULTI_BYTE",
    IsMimeType = "IS_MYME_TYPE",
    IsNumberString = "IS_NUMBER_STRING",
    IsOctal = "IS_OCTAL",
    IsPassportNumber = "IS_PASSPORT_NUMBER",
    IsPhoneNumber = "IS_PHONE_NUMBER",
    IsPort = "IS_PORT",
    IsPostalCode = "IS_POSTAL_CODE",
    IsRFC3339 = "IS_RFC3339",
    IsRgbColor = "IS_RGB_COLOR",
    IsSemVer = "IS_SEM_VER",
    IsSurrogatePair = "IS_SURROGATE_PAIR",
    IsUppercase = "IS_UPPERCASE",
    IsUrl = "IS_URL",
    IsUUID = "IS_UUID",
    IsVariableWidth = "IS_VARIABLE_WIDTH",
    Length = "LENGTH",
    Matches = "MATCHES",
    MaxLength = "MAX_LENGTH",
    MinLength = "MIN_LENGTH",
    NotContains = "NOT_CONTAINS",

    // Typechecker
    IsArray = "IS_ARRAY",
    IsBoolean = "IS_BOOLEAN",
    IsDate = "IS_DATE",
    IsEnum = "IS_ENUM",
    IsInt = "IS_INT",
    IsNumber = "IS_NUMBER",
    IsObject = "IS_OBJECT",
    IsString = "IS_STRING",

}
